version: '3.3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1425OKLNDONO'
      MYSQL_ROOT_PASSWORD: '1425OKLNDONO'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '1425OKLNDONO'
    ports:
      - '8080:80'

volumes:
  my-db:
